# docker-compose.production.yml
version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:


services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: petrmyln/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
  frontend:
    image: petrmyln/foodgram_frontend  # Качаем с Docker Hub
    env_file: .env
    command: sudo cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/foodgram_static
  gateway:
    image: petrmyln/foodgram_gateway  # Качаем с Docker Hub
    env_file: .env
    ports:
      - 8500:80
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/app/media
